apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loopback-pvc
spec:
  storageClassName: local-loopbacks
  accessModes:
    - ReadWriteOnce
  volumeMode: FileSystem
  resources:
    requests:
      storage: 90Mi
