apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-deployments-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-deployments-pods
subjects:
- kind: ServiceAccount
  name: default
