apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: test1-ingress-controller
    namespace: openshift-ingress-operator
  spec:
    replicas: 1
    domain: test1.cluster.example.com
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
          ingressoperator: "test1"
    namespaceSelector:
      matchLabels:
        type: test1
    endpointPublishingStrategy:
      type: HostNetwork
      #type: LoadBalancerService
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
