apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: test2-ingress-controller
    namespace: openshift-ingress-operator
  spec:
    replicas: 1
    domain: test2.cluster.example.com
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
    namespaceSelector:
      matchLabels:
        type: test2
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
