---
apiVersion: v1
kind: Service
metadata:
  name: service-80
spec:
  type: LoadBalancer
  # type: ClusterIP
  selector:
    app: fedora-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
