apiVersion: v1 
kind: Service 
metadata: 
  name: service-80-443 
spec: 
  type: LoadBalancer 
  selector:
    app: fedora-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: tcp80
    - protocol: TCP
      port: 443
      targetPort: 443
      name: tcp443
