apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: not-ready-monitor
  namespace: not-ready-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: not-ready-monitor
subjects:
- kind: ServiceAccount
  name: default
  namespace: not-ready-monitor
