apiVersion: v1
data:
  index.html: |
    Nginx B
kind: ConfigMap
metadata:
  name: nginx-deployment-b
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-b
    service: nginx-deployment-b
  name: nginx-deployment-b
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-b
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-b
  labels:
    app: nginx-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: nginx-b
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: nginx-deployment-b
