apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  storageClassName: "gp2" # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
